# SQL_view.py
wanted data view: '*'
table view: [a_123_drbd,a_456_drbd]

# Input.py
file input: '02_09_15_55_results.txt'
# Key ID: '9'
Client Name: 'a'
Date: '456' #format example:20210101
Disk Type: 'drbd'

# SQL_select.py
wanted data: '*'
table: [a_123_drbd,a_456_drbd]
statement: 'Number_of_Job = "8" AND IOdepth = "8"'

# SQL_chart.py
Select_Data: 'IOPS' # IOPS / MBPS 
Table_Names: 'a_123_drbd'
ReadWrite_Type: '"randwrite"' # read, write, randread, randwrite
Number_of_Job: '"8"'
IOdepth: '"8"'

# chart_readwrite.py
Select_Data_rw: 'IOPS' # IOPS / MBPS 
Table_Names_rw: 'a_123_drbd'
Number_of_Job_rw: '"8"'
IOdepth_rw: '"8"'

# SQL_histogram.py
Select_Data_hist: 'IOPS' # IOPS / MBPS 
Table_hist: [a_123_drbd]
Readwrite_hist: '"read"' # read, write, randread, ranwrite
Number_of_Job_hist: '"8"' 
IOdepth_hist: '"8"'
Blocksize_hist: '"1M"' # 4k / 1M

# SQL_deviation.py
Standard_Value: IOPS # IOPS / MBPS
Table_Name_devi_1: 'a_123_drbd'
ReadWrite_Type_Stan: '"randwrite"' # # read, write, randread, ranwrite
Blocksize_Stan: '"4k"' # used for one standard

Example_Value: IOPS # IOPS / MBPS
Table_Name_devi_2: 'a_123_drbd'
ReadWrite_Type_Ex: '"randwrite"' # # read, write, randread, ranwrite